import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Proyecto Abigail</a>
        </h1>

        <p className={styles.description}>Esto solo es una página para redireccionar. Es el pages/index.js</p>

        <div className={styles.grid}>
          <Link href={"./logIn"}>
            <a className={styles.card}>
              <h2>Módulo LogIn &rarr;</h2>
              <p>Página de LogIn</p>
            </a>
          </Link>

          <Link href={"./home"}>
            <a className={styles.card}>
              <h2>Módulo Home &rarr;</h2>
              <p>Home</p>
            </a>
          </Link>

          <Link href={"./accountsReceivable"}>
            <a className={styles.card}>
              <h2>Módulo de cuentas por cobrar &rarr;</h2>
              <p>Cuentas por cobrar.</p>
            </a>
          </Link>

          <Link href={"./reports"}>
            <a className={styles.card}>
              <h2>Módulo de reportes &rarr;</h2>
              <p>Reportes.</p>
            </a>
          </Link>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer">
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
