// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProyectoAbigail.Models;

#nullable disable

namespace ProyectoAbigail.Migrations
{
    [DbContext(typeof(ConexionContext))]
    partial class ConexionContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ProyectoAbigail.Models.Accion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Estatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha_commit")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Hora_commit")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Accion");
                });

            modelBuilder.Entity("ProyectoAbigail.Models.Cabeza_Famila", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Estatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha_commit")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Hora_commit")
                        .HasColumnType("datetime2");

                    b.Property<int?>("PersonaId")
                        .HasColumnType("int");

                    b.Property<int>("Persona_Id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PersonaId");

                    b.ToTable("Cabeza_Famila");
                });

            modelBuilder.Entity("ProyectoAbigail.Models.Color", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Estatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha_commit")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Hora_commit")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Color");
                });

            modelBuilder.Entity("ProyectoAbigail.Models.Detalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Estatus")
                        .HasColumnType("int");

                    b.Property<int?>("FacturaId")
                        .HasColumnType("int");

                    b.Property<int>("Factura_Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha_commit")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Hora_commit")
                        .HasColumnType("datetime2");

                    b.Property<int?>("InmuebleId")
                        .HasColumnType("int");

                    b.Property<int>("Inmueble_Id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FacturaId");

                    b.HasIndex("InmuebleId");

                    b.ToTable("Detalle");
                });

            modelBuilder.Entity("ProyectoAbigail.Models.Entrada_Salida", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Fecha_commit")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Hora_commit")
                        .HasColumnType("datetime2");

                    b.Property<string>("Matricula")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PersonaId")
                        .HasColumnType("int");

                    b.Property<int>("Persona_Id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PersonaId");

                    b.ToTable("Entrada_Salida");
                });

            modelBuilder.Entity("ProyectoAbigail.Models.Estado_Civil", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Estatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha_commit")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Hora_commit")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Estado_Civil");
                });

            modelBuilder.Entity("ProyectoAbigail.Models.Etnia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Estatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha_commit")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Hora_commit")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Etnia");
                });

            modelBuilder.Entity("ProyectoAbigail.Models.Factura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Estatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha_commit")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Hora_commit")
                        .HasColumnType("datetime2");

                    b.Property<int?>("PersonaId")
                        .HasColumnType("int");

                    b.Property<int>("Persona_Id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PersonaId");

                    b.ToTable("Factura");
                });

            modelBuilder.Entity("ProyectoAbigail.Models.Familia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("Cabeza_FamiliaId")
                        .HasColumnType("int");

                    b.Property<int>("Cabeza_Familia_Id")
                        .HasColumnType("int");

                    b.Property<int>("Estatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha_commit")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Hora_commit")
                        .HasColumnType("datetime2");

                    b.Property<int?>("PersonaId")
                        .HasColumnType("int");

                    b.Property<int>("Persona_Id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Cabeza_FamiliaId");

                    b.HasIndex("PersonaId");

                    b.ToTable("Familia");
                });

            modelBuilder.Entity("ProyectoAbigail.Models.Genero", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Estatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha_commit")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Hora_commit")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Genero");
                });

            modelBuilder.Entity("ProyectoAbigail.Models.Inmueble", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Estatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha_commit")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Hora_commit")
                        .HasColumnType("datetime2");

                    b.Property<string>("Numero_Inmueble")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Precio_Inmueble")
                        .HasColumnType("bigint");

                    b.Property<int?>("SectorId")
                        .HasColumnType("int");

                    b.Property<int>("Sector_Id")
                        .HasColumnType("int");

                    b.Property<int?>("Tipo_InmuebleId")
                        .HasColumnType("int");

                    b.Property<int>("Tipo_Inmueble_Id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SectorId");

                    b.HasIndex("Tipo_InmuebleId");

                    b.ToTable("Inmueble");
                });

            modelBuilder.Entity("ProyectoAbigail.Models.Inmueble_Alquilado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Estatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha_Alquiler")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Fecha_Fin_Alquiler")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Fecha_commit")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Hora_commit")
                        .HasColumnType("datetime2");

                    b.Property<int?>("InmuebleId")
                        .HasColumnType("int");

                    b.Property<int>("Inmueble_Id")
                        .HasColumnType("int");

                    b.Property<int?>("PersonaId")
                        .HasColumnType("int");

                    b.Property<int>("Persona_Id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("InmuebleId");

                    b.HasIndex("PersonaId");

                    b.ToTable("Inmueble_Alquilados");
                });

            modelBuilder.Entity("ProyectoAbigail.Models.Marca", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Estatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha_commit")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Hora_commit")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Marca");
                });

            modelBuilder.Entity("ProyectoAbigail.Models.Modulo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Estatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha_commit")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Hora_commit")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Modulo");
                });

            modelBuilder.Entity("ProyectoAbigail.Models.Permiso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("AccionId")
                        .HasColumnType("int");

                    b.Property<int>("Accion_Id")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Estatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha_commit")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Hora_commit")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ModuloId")
                        .HasColumnType("int");

                    b.Property<int>("Modulo_Id")
                        .HasColumnType("int");

                    b.Property<int?>("RolId")
                        .HasColumnType("int");

                    b.Property<int>("Rol_Id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AccionId");

                    b.HasIndex("ModuloId");

                    b.HasIndex("RolId");

                    b.ToTable("Permiso");
                });

            modelBuilder.Entity("ProyectoAbigail.Models.Persona", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cui")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Estado_Civil_Id")
                        .HasColumnType("int");

                    b.Property<int>("Estatus")
                        .HasColumnType("int");

                    b.Property<int>("Etnia_Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha_Nacimiento")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Fecha_commit")
                        .HasColumnType("datetime2");

                    b.Property<int>("Genero_Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("Hora_commit")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Persona");
                });

            modelBuilder.Entity("ProyectoAbigail.Models.Prop_Vehiculo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Estatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha_commit")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Hora_commit")
                        .HasColumnType("datetime2");

                    b.Property<int?>("PersonaId")
                        .HasColumnType("int");

                    b.Property<int>("Persona_Id")
                        .HasColumnType("int");

                    b.Property<int?>("VehiculoId")
                        .HasColumnType("int");

                    b.Property<int>("Vehiculo_Id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PersonaId");

                    b.HasIndex("VehiculoId");

                    b.ToTable("Prop_Vehiculo");
                });

            modelBuilder.Entity("ProyectoAbigail.Models.Propietario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Estatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha_commit")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Hora_commit")
                        .HasColumnType("datetime2");

                    b.Property<int?>("PersonaId")
                        .HasColumnType("int");

                    b.Property<int>("Persona_Id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PersonaId");

                    b.ToTable("Propietario");
                });

            modelBuilder.Entity("ProyectoAbigail.Models.Reporte", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Estatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha_commit")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Hora_commit")
                        .HasColumnType("datetime2");

                    b.Property<int?>("PersonaId")
                        .HasColumnType("int");

                    b.Property<int>("Persona_Id")
                        .HasColumnType("int");

                    b.Property<int?>("Tipo_ReporteId")
                        .HasColumnType("int");

                    b.Property<int>("Tipo_Reporte_Id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PersonaId");

                    b.HasIndex("Tipo_ReporteId");

                    b.ToTable("Reporte");
                });

            modelBuilder.Entity("ProyectoAbigail.Models.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Estatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha_commit")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Hora_commit")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Rol");
                });

            modelBuilder.Entity("ProyectoAbigail.Models.Rol_Persona", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Estatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha_commit")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Hora_commit")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Rol_Persona");
                });

            modelBuilder.Entity("ProyectoAbigail.Models.Sector", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Estatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha_commit")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Hora_commit")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Sector");
                });

            modelBuilder.Entity("ProyectoAbigail.Models.Tipo_Inmueble", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Estatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha_commit")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Hora_commit")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tipo_Inmueble");
                });

            modelBuilder.Entity("ProyectoAbigail.Models.Tipo_Reporte", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Estatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha_commit")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Hora_commit")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tipo_Reporte");
                });

            modelBuilder.Entity("ProyectoAbigail.Models.Tipo_Vehiculo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Estatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha_commit")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Hora_commit")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tipo_Vehiculo");
                });

            modelBuilder.Entity("ProyectoAbigail.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Estatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha_commit")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Hora_commit")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RolId")
                        .HasColumnType("int");

                    b.Property<int>("Rol_Id")
                        .HasColumnType("int");

                    b.Property<string>("Sal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("User")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RolId");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("ProyectoAbigail.Models.Vehiculo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("ColorId")
                        .HasColumnType("int");

                    b.Property<int>("Color_Id")
                        .HasColumnType("int");

                    b.Property<int>("Estatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha_commit")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Hora_commit")
                        .HasColumnType("datetime2");

                    b.Property<int?>("MarcaId")
                        .HasColumnType("int");

                    b.Property<int>("Marca_Id")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Tipo_VehiculoId")
                        .HasColumnType("int");

                    b.Property<string>("anio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ColorId");

                    b.HasIndex("MarcaId");

                    b.HasIndex("Tipo_VehiculoId");

                    b.ToTable("Vehiculo");
                });

            modelBuilder.Entity("ProyectoAbigail.Models.Cabeza_Famila", b =>
                {
                    b.HasOne("ProyectoAbigail.Models.Persona", "Persona")
                        .WithMany()
                        .HasForeignKey("PersonaId");

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("ProyectoAbigail.Models.Detalle", b =>
                {
                    b.HasOne("ProyectoAbigail.Models.Factura", "Factura")
                        .WithMany()
                        .HasForeignKey("FacturaId");

                    b.HasOne("ProyectoAbigail.Models.Inmueble", "Inmueble")
                        .WithMany()
                        .HasForeignKey("InmuebleId");

                    b.Navigation("Factura");

                    b.Navigation("Inmueble");
                });

            modelBuilder.Entity("ProyectoAbigail.Models.Entrada_Salida", b =>
                {
                    b.HasOne("ProyectoAbigail.Models.Persona", "Persona")
                        .WithMany()
                        .HasForeignKey("PersonaId");

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("ProyectoAbigail.Models.Factura", b =>
                {
                    b.HasOne("ProyectoAbigail.Models.Persona", "Persona")
                        .WithMany()
                        .HasForeignKey("PersonaId");

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("ProyectoAbigail.Models.Familia", b =>
                {
                    b.HasOne("ProyectoAbigail.Models.Cabeza_Famila", "Cabeza_Familia")
                        .WithMany()
                        .HasForeignKey("Cabeza_FamiliaId");

                    b.HasOne("ProyectoAbigail.Models.Persona", "Persona")
                        .WithMany()
                        .HasForeignKey("PersonaId");

                    b.Navigation("Cabeza_Familia");

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("ProyectoAbigail.Models.Inmueble", b =>
                {
                    b.HasOne("ProyectoAbigail.Models.Sector", "Sector")
                        .WithMany()
                        .HasForeignKey("SectorId");

                    b.HasOne("ProyectoAbigail.Models.Tipo_Inmueble", "Tipo_Inmueble")
                        .WithMany()
                        .HasForeignKey("Tipo_InmuebleId");

                    b.Navigation("Sector");

                    b.Navigation("Tipo_Inmueble");
                });

            modelBuilder.Entity("ProyectoAbigail.Models.Inmueble_Alquilado", b =>
                {
                    b.HasOne("ProyectoAbigail.Models.Inmueble", "Inmueble")
                        .WithMany()
                        .HasForeignKey("InmuebleId");

                    b.HasOne("ProyectoAbigail.Models.Persona", "Persona")
                        .WithMany()
                        .HasForeignKey("PersonaId");

                    b.Navigation("Inmueble");

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("ProyectoAbigail.Models.Permiso", b =>
                {
                    b.HasOne("ProyectoAbigail.Models.Accion", "Accion")
                        .WithMany()
                        .HasForeignKey("AccionId");

                    b.HasOne("ProyectoAbigail.Models.Modulo", "Modulo")
                        .WithMany()
                        .HasForeignKey("ModuloId");

                    b.HasOne("ProyectoAbigail.Models.Rol", "Rol")
                        .WithMany()
                        .HasForeignKey("RolId");

                    b.Navigation("Accion");

                    b.Navigation("Modulo");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("ProyectoAbigail.Models.Prop_Vehiculo", b =>
                {
                    b.HasOne("ProyectoAbigail.Models.Persona", "Persona")
                        .WithMany()
                        .HasForeignKey("PersonaId");

                    b.HasOne("ProyectoAbigail.Models.Vehiculo", "Vehiculo")
                        .WithMany()
                        .HasForeignKey("VehiculoId");

                    b.Navigation("Persona");

                    b.Navigation("Vehiculo");
                });

            modelBuilder.Entity("ProyectoAbigail.Models.Propietario", b =>
                {
                    b.HasOne("ProyectoAbigail.Models.Persona", "Persona")
                        .WithMany()
                        .HasForeignKey("PersonaId");

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("ProyectoAbigail.Models.Reporte", b =>
                {
                    b.HasOne("ProyectoAbigail.Models.Persona", "Persona")
                        .WithMany()
                        .HasForeignKey("PersonaId");

                    b.HasOne("ProyectoAbigail.Models.Tipo_Reporte", "Tipo_Reporte")
                        .WithMany()
                        .HasForeignKey("Tipo_ReporteId");

                    b.Navigation("Persona");

                    b.Navigation("Tipo_Reporte");
                });

            modelBuilder.Entity("ProyectoAbigail.Models.Usuario", b =>
                {
                    b.HasOne("ProyectoAbigail.Models.Rol", "Rol")
                        .WithMany()
                        .HasForeignKey("RolId");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("ProyectoAbigail.Models.Vehiculo", b =>
                {
                    b.HasOne("ProyectoAbigail.Models.Color", "Color")
                        .WithMany()
                        .HasForeignKey("ColorId");

                    b.HasOne("ProyectoAbigail.Models.Marca", "Marca")
                        .WithMany()
                        .HasForeignKey("MarcaId");

                    b.HasOne("ProyectoAbigail.Models.Tipo_Vehiculo", "Tipo_Vehiculo")
                        .WithMany()
                        .HasForeignKey("Tipo_VehiculoId");

                    b.Navigation("Color");

                    b.Navigation("Marca");

                    b.Navigation("Tipo_Vehiculo");
                });
#pragma warning restore 612, 618
        }
    }
}
